server:
    port: 9999
    ssl:
        key-password: zaq1@WSX
        key-store-password: zaq1@WSX
        key-store: src/main/resources/static/keystore.jks
spring:
    mail:
        host: smtp.gmail.com
        username: oibipk@gmail.com
        password: ?53hrJy3aDoQH?B?
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/beauty-space
        username: postgres
        password: postgres
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
