server:
    port: 8080
spring:
    datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
