server:
    port: 9999
    ssl:
        key-password: zaq1@WSX
        key-store-password: zaq1@WSX
        key-store: src/main/resources/static/keystore.jks
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/beauty-space
        username: postgres
        password: postgres
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
